print("Warren Iowa Sentiment:")
print(table(EW_IA_sent$Sentiment))
print("Harris Iowa Sentiment:")
print(table(KH_IA_sent$Sentiment))
print("Buttigieg Iowa Sentiment:")
print(table(PB_IA_sent$Sentiment))
print("Biden Iowa Sentiment:")
print(table(JB_IA_sent$Sentiment))
print("Sanders New Hampshire Sentiment:")
print(table(BS_NH_sent$Sentiment))
print("Warren New Hampshire Sentiment:")
print(table(EW_NH_sent$Sentiment))
print("Harris New Hampshire Sentiment:")
print(table(KH_NH_sent$Sentiment))
print("Buttigieg South Carolina Sentiment:")
print(table(PB_SC_sent$Sentiment))
print("Biden South Carolina Sentiment:")
print(table(JB_SC_sent$Sentiment))
print("Sanders Nevada Sentiment:")
print(table(BS_NV_sent$Sentiment))
print("Warren Nevada Sentiment:")
print(table(EW_NV_sent$Sentiment))
print("Harris Nevada Sentiment:")
print(table(KH_NV_sent$Sentiment))
print("Buttigieg Nevada Sentiment:")
print(table(PB_NV_sent$Sentiment))
print("Biden Nevada Sentiment:")
print(table(JB_NV_sent$Sentiment))